name: random_cue_focus_windows
description: A science-informed random cue focus timer for Windows desktop.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
